require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb
  Max: 20

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - db/migrate/*.rb

Metrics/LineLength:
  Exclude:
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
  Max: 15

Metrics/ParameterLists:
  Max: 8

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
