AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/simple_form.rb
    - config/routes.rb
    - db/migrate/*.rb

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Exclude:
    - config/initializers/devise.rb
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - app/models/ability.rb
    - db/migrate/*.rb
  Max: 15

Metrics/ParameterLists:
  Max: 10

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false
