development:
  adapter: redis
  url: <%= ENV['REDIS_HOST'] %>
  channel_prefix: nativegap_development

test:
  adapter: redis
  channel_prefix: nativegap_test

production:
  adapter: redis
  url: <%= ENV['REDIS_HOST'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  channel_prefix: nativegap_production
