development:
  adapter: redis
  url: <%= Rails.application.credentials.development[:redis][:host] %>
  channel_prefix: nativegap_development

test:
  adapter: redis
  channel_prefix: nativegap_test

production:
  adapter: redis
  url: <%= Rails.application.credentials.production[:redis][:host] %>
  password: <%= Rails.application.credentials.production[:redis][:password] %>
  channel_prefix: nativegap_production
