nativegap:
  delay:
    build: <%= 30.seconds %>
    phonegap: <%= 2.minutes %>
  socials:
    twitter: https://twitter.com/native_gap
    youtube: https://www.youtube.com/channel/UCIEedde7D9ea39nBEHIcLTw
  pricing:
    android:
      starter: 7
      pro: 20
    ios:
      starter: 7
      pro: 20
  medium:
    blog: https://medium.com/nativegap/blog
    help: https://medium.com/nativegap/help
    changelog: https://medium.com/nativegap/changelog
  terms: https://jonhue.me/nativegap/terms
  privacy: https://jonhue.me/nativegap/privacy

mailgun:
  domain: nativegap.com
  emails:
    with: with@nativegap.com
    support: support@nativegap.com
