# => http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/

development:
  :timeout: 8
  :concurrency: 47
  :queues:
    - app
    - cable
    - carrierwave

production:
  :timeout: 8
  :concurrency: 6
  :queues:
    - app
    - cable
    - carrierwave
